api_lol_homepage:
    path:     /
    defaults: { _controller: LolBundle:Api\Meme:index }
    methods:  [GET]

api_lol_show_meme:
    path:     /meme/{id}
    defaults: { _controller: LolBundle:Api\Meme:show }
    methods:  [GET]
    requirements:
        id: \d+

api_lol_remove_meme:
    path:     /meme/{id}/remove
    defaults: { _controller: LolBundle:Api\Meme:remove }
    methods:  [DELETE]
    requirements:
        id: \d+

api_lol_remove_comment:
    path:     /meme/{id}/comment/{comment_id}
    defaults: { _controller: LolBundle:Api\Meme:removeComment }
    methods:  [DELETE]
    requirements:
        id: \d+
        comment_id: \d+

api_lol_create_meme:
    path:     /meme
    defaults: { _controller: LolBundle:Api\Meme:create }
    methods:  [POST]

api_lol_comment_meme:
    path:     /meme/{id}/comment
    defaults: { _controller: LolBundle:Api\Meme:comment }
    methods:  [POST]
    requirements:
        id: \d+

api_lol_note_meme:
    path: /meme/{id}/{note}
    defaults: { _controller: LolBundle:Api\Meme:note }
    methods:  [GET]
    requirements:
        id: \d+
        note: upvote|downvote

api_lol_register_user:
    path: /register
    defaults: { _controller: LolBundle:Api\User:register }
    methods: [POST]

api_lol_show_user:
    path: /user
    defaults: { _controller: LolBundle:Api\User:show }
    methods: [GET]