#LolBundle\Entity\Meme:
#    attributes:
#        id:
#            groups: ['meme', 'price']
#        title:
#            groups: ['place', 'price']
#        address:
#            groups: ['place', 'price']
#        comments:
#            groups: ['meme']


#AppBundle\Entity\Price:
#    attributes:
#        id:
#            groups: ['place', 'price']
#        type:
#            groups: ['place', 'price']
#        value:
#            groups: ['place', 'price']
#        place:
#            groups: ['price']