services:
    lol.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    lol.normalizer.meme:
        class: LolBundle\Service\MemeNormalizer

    lol.normalizer.comment:
        class: LolBundle\Service\CommentNormalizer

    lol.normalizer.user:
        class: LolBundle\Service\UserNormalizer


    lol.serializer.default:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            0:
                - '@lol.normalizer.meme'
                - '@lol.normalizer.comment'
                - '@lol.normalizer.user'
            1:
                - '@lol.encoder.json'

    meme_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LolBundle\Entity\Meme

    comment_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - LolBundle\Entity\Comment

    meme_reader:
        class: LolBundle\Service\MemeReader
        arguments:
            - '@meme_repository'

    meme_factory:
        class: LolBundle\Service\MemeFactory
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    meme_commenter:
        class: LolBundle\Service\MemeCommenter
        arguments:
            - '@doctrine.orm.entity_manager'

    comment_reader:
        class: LolBundle\Service\CommentReader
        arguments:
            - '@comment_repository'

    meme_note:
        class: LolBundle\Service\MemeNote
        arguments:
            - '@doctrine.orm.entity_manager'

    user_creator:
        class: LolBundle\Service\UserCreator
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.password_encoder'