services:
    lol.encoder.json:
        class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

    lol.normalizer.meme:
        class: 'LolBundle\Service\MemeNormalizer'

    lol.normalizer.comment:
        class: 'LolBundle\Service\CommentNormalizer'

    lol.normalizer.user:
        class: 'LolBundle\Service\UserNormalizer'


    lol.serializer.default:
        class: 'Symfony\Component\Serializer\Serializer'
        arguments:
            0:
                - '@lol.normalizer.meme'
                - '@lol.normalizer.comment'
                - '@lol.normalizer.user'
            1:
                - '@lol.encoder.json'