login:
    path:     /login
    defaults: { _controller: LolBundle:User:login }

logout:
    path:     /logout

lol:
    resource: "@LolBundle/Resources/config/routing.yml"
    prefix:   /

lol_api:
    resource: "@LolBundle/Resources/config/api_routing.yml"
    prefix:   /api
