# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    negotiator:
        class: LolBundle\Service\MediaTypeNegotiator
    app.token_authenticator:
        class: LolBundle\Security\TokenAuthenticator
    #api_key_user_provider:
    #    class: LolBundle\Security\ApiKeyUserProvider
    #api_key_authenticator:
    #    class:  LolBundle\Security\ApiKeyAuthenticator
    #    public: false
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#    _defaults:
#        autowire: true
#        autoconfigure: true
#        public: false
#        abstract: true
##
##    LolBundle\:
##        resource: '../../src/LolBundle/*'
##        # you can exclude directories or files
##        # but if a service is unused, it's removed anyway
##        exclude: '../../src/LolBundle/{Entity,Repository}'
##
#    LolBundle\Controller\:
#        resource: '../../src/LolBundle/Controller'
#        public: true
#        #tags: ['controller.service_arguments']
#
#    LolBundle\Service\MediaTypeNegotiator: '@negotiator'