LolBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: LolBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        date:
            type: datetime
    manyToOne:
        meme:
            targetEntity: LolBundle\Entity\Meme
            inversedBy: comments
            joinColumn:
                name: meme_id
                referencedColumnName: id
        user:
            targetEntity: LolBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
