LolBundle\Entity\Meme:
    type: entity
    table: null
    repositoryClass: LolBundle\Repository\MemeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        image:
            type: string
            length: 255
        nbUpVote:
            type: integer
            nullable: true
        nbDownVote:
            type: integer
            nullable: true
        date:
            type: datetime

    oneToMany:
        comments:
            targetEntity: LolBundle\Entity\Comment
            mappedBy: meme

    manyToOne:
        user:
            targetEntity: LolBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
