<?php

namespace LolBundle\Repository;

/**
 * MemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemeRepository extends \Doctrine\ORM\EntityRepository
{
}
